[tool.pylint."MESSAGES CONTROL"]
# Keep convention messages enabled so style suggestions are shown
# Example to quiet specific ones later: disable = ["C0114","C0115","C0116"]

[tool.pylint.FORMAT]
max-line-length = 100

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src/popy"]
known_first_party = ["popy"]

[tool.black]
line-length = 100
target-version = ["py311"]

